<a href="https://colab.research.google.com/github/aditya-shriwastava/colab-notebooks/blob/master/AOC_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Advent of Code 2021](https://adventofcode.com/2021)

In [157]:
import numpy as np
from tqdm import tqdm

# Problem *1*

## Part 1

In [ ]:
#@title input
%%file input_p1.txt
140
154
165
150
151
161
172
174
166
168
176
191
192
189
190
191
202
203
206
207
167
179
204
206
208
209
216
198
200
207
217
218
223
227
228
243
241
246
278
255
256
273
295
291
288
290
303
325
301
292
291
309
313
315
319
339
340
327
336
335
340
331
334
316
317
323
324
323
312
298
291
285
288
266
267
266
258
259
257
259
250
265
270
267
271
272
277
281
277
284
291
283
284
291
292
278
285
296
294
297
298
301
300
311
310
322
320
337
334
333
331
317
323
358
362
364
371
383
424
427
438
443
441
445
444
440
458
460
459
457
455
446
440
439
438
430
422
424
438
449
450
451
443
459
458
479
473
471
478
496
498
488
512
513
523
545
544
543
539
540
553
554
553
561
565
572
576
584
586
591
603
585
600
601
599
596
587
586
587
588
598
601
599
596
588
589
595
588
586
591
598
595
597
616
615
599
598
576
570
573
599
600
601
602
604
605
617
608
607
606
607
605
604
603
601
602
584
590
597
596
600
583
579
582
576
580
583
581
582
558
566
562
581
589
570
571
566
562
564
565
567
564
557
565
566
562
564
567
568
570
554
546
548
511
510
509
507
500
513
510
513
500
502
508
527
531
539
538
545
546
548
555
557
558
561
566
567
571
570
605
627
625
615
617
588
597
599
598
609
612
611
615
617
618
630
622
619
627
674
691
695
715
734
736
737
739
753
751
759
762
732
709
711
730
733
729
746
752
755
756
791
792
793
790
786
808
811
844
834
846
820
821
838
842
844
835
840
843
844
836
837
841
843
852
863
865
870
868
863
865
868
875
886
904
909
917
905
906
905
920
919
917
911
924
899
900
915
923
940
941
921
922
896
908
911
893
892
912
896
900
882
884
901
902
901
907
886
889
888
898
899
896
899
883
900
893
929
907
911
916
910
912
906
911
915
920
921
923
921
922
905
923
922
938
939
941
940
931
960
966
973
986
988
1008
1016
1014
987
993
1004
1006
1004
1024
1031
1032
1034
1025
1022
1008
1007
1010
1009
997
1002
1007
1010
1018
1014
1016
1023
1031
1032
1048
1049
1056
1055
1064
1065
1084
1081
1084
1088
1090
1109
1115
1144
1146
1144
1142
1143
1160
1158
1163
1167
1183
1184
1195
1182
1181
1169
1181
1175
1188
1187
1188
1189
1187
1195
1196
1197
1216
1215
1223
1222
1209
1218
1223
1222
1225
1196
1193
1198
1200
1208
1207
1216
1202
1197
1172
1164
1178
1179
1167
1177
1178
1175
1178
1191
1198
1200
1208
1212
1215
1225
1233
1240
1243
1235
1237
1244
1245
1248
1249
1251
1250
1256
1261
1262
1244
1250
1240
1234
1225
1229
1216
1213
1214
1206
1209
1211
1205
1228
1230
1232
1233
1226
1216
1204
1194
1196
1165
1176
1186
1198
1195
1204
1218
1216
1219
1220
1225
1229
1227
1231
1241
1244
1241
1249
1248
1253
1254
1247
1248
1249
1258
1266
1270
1269
1283
1298
1295
1306
1309
1330
1335
1339
1326
1327
1291
1302
1301
1313
1314
1315
1318
1315
1316
1315
1338
1336
1341
1347
1343
1368
1374
1377
1378
1383
1384
1367
1368
1367
1378
1371
1372
1373
1365
1367
1366
1369
1365
1367
1361
1360
1368
1366
1363
1366
1374
1380
1364
1339
1341
1340
1339
1340
1341
1348
1356
1358
1359
1351
1356
1345
1322
1323
1324
1325
1326
1336
1335
1331
1330
1339
1331
1329
1346
1343
1350
1357
1358
1334
1336
1335
1338
1348
1346
1363
1365
1368
1365
1386
1383
1381
1383
1379
1386
1381
1384
1378
1379
1372
1389
1393
1389
1414
1415
1414
1405
1417
1418
1415
1427
1429
1428
1447
1430
1426
1425
1410
1412
1413
1427
1424
1413
1401
1402
1423
1431
1436
1440
1447
1446
1447
1446
1447
1446
1451
1450
1451
1450
1446
1451
1456
1453
1456
1459
1490
1494
1493
1502
1504
1524
1523
1522
1539
1546
1545
1552
1554
1555
1557
1563
1562
1566
1567
1566
1567
1566
1565
1568
1570
1572
1573
1586
1588
1590
1591
1589
1607
1608
1595
1596
1595
1594
1599
1604
1612
1608
1609
1606
1603
1602
1601
1613
1597
1598
1585
1604
1625
1626
1627
1634
1636
1637
1642
1637
1638
1630
1632
1631
1630
1639
1640
1668
1647
1663
1668
1646
1653
1665
1667
1668
1671
1679
1673
1678
1679
1684
1677
1678
1688
1687
1686
1691
1697
1699
1705
1717
1685
1708
1707
1708
1706
1709
1699
1700
1699
1710
1709
1708
1714
1728
1721
1715
1717
1694
1706
1720
1722
1730
1722
1728
1730
1737
1755
1763
1747
1742
1743
1727
1736
1730
1742
1744
1734
1726
1707
1720
1719
1725
1683
1682
1683
1688
1682
1681
1682
1684
1689
1649
1650
1652
1655
1662
1665
1666
1667
1689
1684
1677
1678
1667
1666
1670
1672
1670
1675
1672
1659
1660
1689
1688
1691
1696
1687
1689
1688
1689
1690
1695
1705
1710
1713
1715
1706
1703
1707
1683
1677
1670
1664
1675
1676
1681
1682
1679
1673
1678
1668
1685
1703
1716
1712
1709
1715
1720
1730
1735
1741
1754
1740
1749
1750
1753
1746
1753
1768
1780
1781
1818
1821
1831
1830
1838
1839
1838
1843
1829
1833
1835
1847
1845
1849
1850
1852
1828
1830
1836
1839
1855
1857
1837
1838
1843
1830
1825
1848
1838
1840
1843
1831
1813
1816
1815
1810
1809
1817
1816
1818
1806
1802
1803
1807
1805
1770
1759
1757
1756
1759
1751
1752
1753
1747
1755
1762
1766
1767
1777
1778
1772
1784
1783
1789
1795
1797
1823
1824
1820
1823
1824
1843
1866
1868
1864
1860
1861
1864
1862
1849
1850
1862
1860
1862
1863
1862
1870
1893
1896
1897
1888
1889
1913
1914
1911
1924
1928
1943
1958
1957
1951
1939
1929
1931
1930
1928
1930
1946
1954
1955
1944
1934
1935
1950
1957
1956
1957
1958
1952
1951
1954
1953
1941
1949
1950
1968
1961
1960
1955
1949
1946
1918
1919
1920
1933
1934
1936
1937
1942
1913
1919
1920
1921
1925
1924
1925
1932
1935
1937
1927
1913
1916
1922
1906
1907
1908
1901
1897
1901
1899
1900
1902
1903
1896
1901
1904
1909
1901
1912
1914
1910
1913
1914
1915
1917
1921
1922
1920
1919
1912
1909
1911
1908
1909
1950
1953
1983
1989
1993
1992
1994
1997
1980
1990
1991
2011
2016
2015
2026
2030
2033
2044
2039
2040
2042
2044
2053
2054
2033
2030
2029
2030
2013
2016
2027
2021
2017
2018
2011
2009
2008
2007
2004
1994
1992
1973
1974
1969
1963
1968
1969
1967
1980
1981
1984
1981
1977
1982
2002
2007
2003
2000
2019
2013
2014
2017
2054
2081
2079
2077
2078
2064
2063
2065
2061
2051
2069
2095
2093
2098
2095
2084
2085
2087
2088
2082
2080
2081
2082
2079
2068
2072
2073
2092
2096
2097
2078
2083
2090
2081
2093
2077
2084
2087
2074
2075
2061
2052
2058
2065
2052
2053
2055
2067
2063
2072
2077
2075
2081
2082
2089
2109
2110
2107
2102
2098
2085
2089
2091
2097
2087
2077
2073
2079
2074
2076
2077
2078
2061
2076
2077
2080
2091
2074
2075
2080
2085
2090
2095
2103
2106
2108
2116
2120
2128
2129
2130
2146
2153
2166
2165
2169
2173
2158
2149
2154
2162
2161
2162
2164
2165
2166
2167
2159
2180
2181
2177
2193
2208
2206
2214
2216
2239
2218
2219
2228
2203
2204
2212
2211
2219
2227
2228
2229
2230
2231
2228
2237
2236
2245
2246
2244
2252
2262
2260
2270
2269
2270
2289
2290
2313
2289
2292
2293
2295
2300
2301
2302
2314
2317
2329
2330
2310
2313
2314
2293
2294
2299
2300
2323
2325
2320
2317
2323
2310
2296
2297
2293
2320
2310
2311
2315
2319
2320
2328
2338
2345
2349
2370
2374
2376
2375
2370
2372
2373
2374
2377
2388
2392
2355
2361
2397
2398
2386
2400
2398
2399
2383
2384
2394
2397
2400
2401
2406
2409
2411
2426
2447
2441
2443
2418
2417
2418
2407
2408
2409
2423
2420
2394
2393
2401
2410
2404
2423
2429
2431
2432
2405
2406
2407
2400
2401
2390
2389
2391
2387
2388
2399
2415
2416
2421
2420
2424
2432
2436
2419
2422
2421
2411
2426
2427
2441
2433
2439
2431
2429
2431
2434
2442
2456
2439
2440
2443
2452
2453
2456
2459
2458
2470
2471
2470
2471
2474
2475
2480
2477
2473
2472
2501
2500
2507
2516
2530
2548
2557
2589
2587
2589
2593
2598
2600
2603
2605
2604
2605
2606
2614
2615
2623
2626
2638
2632
2635
2641
2642
2641
2660
2661
2685
2683
2689
2693
2674
2676
2698
2727
2725
2716
2735
2729
2753
2756
2765
2766
2774
2775
2774
2775
2779
2785
2806
2803
2813
2803
2801
2802
2781
2782
2780
2785
2788
2784
2779
2755
2758
2759
2773
2774
2776
2779
2802
2787
2781
2785
2779
2778
2776
2779
2781
2777
2772
2771
2756
2758
2764
2776
2775
2768
2771
2769
2764
2765
2764
2754
2755
2753
2767
2770
2774
2783
2782
2783
2778
2782
2784
2775
2778
2774
2773
2774
2776
2784
2796
2797
2796
2807
2798
2799
2800
2801
2802
2805
2817
2818
2809
2819
2818
2800
2796
2795
2796
2797
2799
2805
2833
2835
2804
2809
2810
2784
2806
2815
2824
2849
2837
2832
2831
2839
2841
2843
2844
2856
2855
2858
2857
2852
2858
2850
2845
2841
2831
2825
2818
2820
2819
2822
2831
2832
2825
2824
2821
2822
2807
2808
2810
2823
2811
2821
2813
2822
2810
2818
2824
2837
2851
2852
2835
2831
2832
2820
2801
2802
2803
2812
2840
2838
2841
2843
2846
2854
2856
2857
2886
2900
2906
2907
2902
2910
2918
2925
2926
2924
2925
2918
2925
2913
2912
2932
2938
2936
2941
2948
2950
2951
2954
2958
2961
2966
2995
2999
3005
3017
3025
3024
3025
3027
3030
3034
3030
3032
3035
3034
3033
3032
3033
3024
3027
3028
3029
3030
3034
3064
3050
3056
3053
3065
3072
3067
3065
3068
3086
3089
3100
3109
3104
3105
3108
3098
3105
3110
3111
3129
3137
3138
3121
3113
3125
3133
3135
3137
3143
3133
3134
3133
3137
3145
3164
3169
3170
3184
3165
3168
3166
3159
3158
3165
3162
3145
3133
3134
3149
3153
3151
3158
3160
3161
3164
3165
3159
3145
3146
3147
3148
3131
3140
3148
3144
3167
3149
3150
3142
3115
3129
3134
3136
3141
3164
3165
3162
3161
3169
3170
3169
3171
3167
3173
3181
3186
3187
3186
3190
3191
3193
3194
3204
3205
3222
3221
3231
3232
3233
3234
3231
3240
3246
3258
3260
3277
3278
3274
3275
3273
3276
3270
3290
3292
3300
3320
3324
3323
3321
3320
3301
3308
3305
3306
3301
3309
3306
3327
3334
3333
3338
3339
3341
3342
3353
3325
3333
3342
3329
3330
3323
3320
3334
3347
3336
3324
3330
3328
3324
3321
3322
3325
3311
3313
3311
3340
3342
3346
3350
3351
3334
3360
3344
3347
3341
3344
3358
3350
3344
3354
3349
3363
3380
3372
3375
3369
3365
3376
3375
3381
3380
3385
3405
3407
3408
3411
3406
3408
3410
3414
3438
3459
3456
3457
3449
3452
3455
3460
3465
3466
3468
3466
3465
3466
3467
3472
3468
3462
3489
3492
3494
3470
3466
3478
3494
3481
3497
3498
3499
3500
3502
3492
3489
3502
3503
3518
3523
3526
3534
3536
3542
3545
3548
3549
3551
3554
3546
3570
3584
3585
3552
3551
3558
3559
3560
3558
3551
3556
3549
3541
3544
3559
3577
3581
3562
3564
3565
3547
3551
3552
3557
3569
3571
3563
3575
3587
3591
3595
3596

Writing input_p1.txt


In [ ]:
with open('input_p1.txt', 'r') as fd:
  lines = fd.readlines()
  input = [int(line) for line in lines]

In [ ]:
print(len(input))

2000


In [ ]:
last = None
increased = 0
for x in input:
  if last is not None:
    if x > last:
      increased += 1
  last = x

print(increased)

1298


## Part 2

In [ ]:
print(607+618+618)
print(618+618+617)

1843
1853


In [ ]:
window_sums = []
for i in range(len(input) - 2):
  window_sums.append(input[i] + input[i+1] + input[i+2])

print(len(window_sums)) 

1998


In [ ]:
last = None
increased = 0
for x in window_sums:
  if last is not None:
    if x > last:
      increased += 1
  last = x

print(increased)

1248


# Problem 2

## Part 1

In [ ]:
#@title Input
%%file input_p2.txt
forward 8
forward 3
down 8
down 2
up 1
up 4
down 9
forward 3
forward 4
forward 5
forward 1
forward 1
up 8
forward 2
forward 9
down 2
forward 8
down 5
down 3
down 8
up 1
forward 1
down 8
up 7
down 8
down 9
down 4
down 7
forward 7
forward 9
down 2
down 5
forward 1
down 1
forward 2
up 8
down 8
forward 2
up 5
down 6
down 5
down 2
forward 5
forward 4
forward 6
down 4
up 1
down 8
down 7
down 3
down 4
down 5
forward 7
down 3
down 3
forward 3
down 2
up 8
up 8
forward 2
down 8
down 8
forward 3
forward 9
forward 3
forward 2
down 9
down 3
forward 4
forward 1
down 7
forward 5
up 2
down 6
up 4
down 2
up 5
forward 6
down 6
down 1
forward 5
forward 4
up 8
up 5
forward 2
down 5
down 4
up 1
forward 9
up 5
up 5
forward 3
down 6
forward 7
down 2
forward 1
forward 4
forward 4
down 2
down 6
down 3
down 1
forward 1
down 8
forward 2
down 1
down 2
forward 6
forward 1
forward 7
forward 2
down 2
up 6
up 2
forward 7
down 6
down 1
forward 5
forward 3
forward 1
down 3
up 1
forward 3
forward 1
down 2
down 5
up 8
down 8
forward 3
down 9
forward 8
down 8
down 5
forward 2
up 1
down 3
up 3
down 5
down 7
down 8
down 8
down 1
forward 9
up 4
up 4
down 5
forward 6
forward 1
up 6
forward 5
up 6
forward 1
forward 9
down 3
down 8
forward 6
forward 6
up 1
down 6
forward 2
down 7
down 2
forward 4
up 4
up 2
forward 8
up 6
down 8
up 3
down 5
down 3
forward 3
down 8
up 4
up 5
down 1
down 7
down 7
forward 6
up 6
down 1
forward 7
down 2
up 7
up 3
forward 9
down 3
up 4
up 1
forward 8
down 4
forward 9
forward 8
down 4
down 3
down 1
forward 8
up 7
down 3
up 5
down 3
down 9
down 9
up 9
down 9
up 4
down 5
down 5
forward 8
forward 1
up 3
down 9
down 8
forward 2
forward 1
up 6
down 3
forward 1
up 6
forward 9
forward 3
forward 3
down 2
down 7
forward 1
up 9
up 3
forward 1
forward 2
forward 7
forward 8
forward 2
forward 3
forward 1
forward 7
down 1
up 7
up 3
forward 3
forward 9
down 7
down 3
forward 2
forward 8
up 1
forward 2
forward 3
up 2
down 1
down 9
down 4
up 3
forward 3
down 6
down 1
forward 2
down 8
forward 3
forward 9
forward 1
forward 6
forward 5
down 5
forward 2
up 7
up 7
down 8
forward 9
up 1
up 5
up 8
forward 5
forward 2
down 5
up 5
down 3
forward 6
down 9
down 7
forward 2
forward 8
forward 3
down 7
down 8
forward 9
down 3
down 3
forward 1
forward 4
down 2
forward 1
forward 3
forward 5
down 9
up 3
down 5
forward 8
forward 3
down 5
forward 3
forward 7
down 3
forward 8
down 1
down 3
down 4
down 2
forward 8
down 2
forward 5
down 2
up 2
forward 8
forward 9
forward 3
forward 2
forward 3
down 2
forward 5
down 1
down 9
up 1
down 6
forward 2
up 1
forward 6
down 2
forward 2
forward 1
forward 4
forward 4
forward 9
forward 2
down 5
forward 9
forward 1
forward 7
forward 1
down 7
forward 7
down 4
down 8
down 8
down 1
forward 4
down 5
up 3
down 5
forward 6
down 6
down 4
down 9
down 4
down 5
forward 7
up 4
forward 6
down 9
down 5
down 5
up 2
forward 8
up 5
down 1
down 2
up 6
down 7
forward 7
up 5
forward 4
up 5
down 3
up 7
forward 4
down 4
down 5
down 7
down 3
down 9
up 8
down 9
forward 6
forward 2
forward 2
up 8
up 2
down 4
down 4
up 7
up 9
forward 2
forward 8
forward 4
up 8
forward 8
up 2
down 3
forward 9
down 1
down 7
forward 4
down 2
up 6
up 6
down 9
forward 6
forward 9
down 3
forward 8
up 1
down 5
forward 1
down 6
up 8
forward 2
up 7
forward 5
down 5
up 3
forward 2
forward 1
forward 4
down 6
up 9
forward 9
down 8
forward 2
down 1
down 3
forward 2
forward 9
up 1
forward 9
down 4
forward 2
forward 7
forward 1
up 2
up 2
down 9
forward 3
forward 2
down 6
up 8
down 4
forward 8
up 9
up 6
down 5
up 1
down 9
down 2
down 1
up 8
down 1
forward 3
down 7
down 7
forward 8
down 4
forward 1
forward 4
forward 5
down 8
down 2
down 9
up 5
down 8
down 8
down 3
forward 2
down 5
up 5
down 1
down 2
forward 9
down 7
down 7
down 1
down 6
up 6
up 7
down 1
down 3
down 2
down 5
down 9
down 4
down 5
forward 1
up 7
down 7
forward 6
forward 4
down 3
forward 3
forward 6
forward 7
down 3
forward 1
down 6
down 8
forward 3
up 3
forward 4
forward 3
down 6
up 7
forward 8
forward 4
down 7
down 6
down 8
forward 9
down 6
down 5
up 4
down 6
down 8
down 5
up 4
forward 2
forward 8
forward 9
down 2
forward 5
down 9
down 2
down 7
forward 2
down 2
up 7
down 2
up 5
forward 3
down 8
forward 3
forward 8
up 3
down 6
down 1
forward 2
up 7
down 8
forward 8
down 2
down 3
down 5
forward 4
forward 5
down 2
forward 2
down 5
down 9
forward 4
forward 3
forward 2
down 9
forward 2
forward 9
down 5
down 9
down 6
down 6
down 3
down 1
down 7
forward 7
forward 2
up 9
forward 4
up 7
forward 3
down 2
up 8
up 3
down 4
up 9
forward 1
down 1
forward 4
up 4
forward 4
up 8
forward 7
down 3
forward 1
up 3
up 1
up 2
down 3
forward 5
down 6
down 1
down 2
forward 2
down 3
up 1
forward 4
down 2
forward 8
forward 3
forward 7
forward 7
down 5
down 7
forward 8
up 2
down 6
forward 1
down 4
forward 5
forward 8
forward 9
forward 7
down 1
down 3
down 1
down 2
forward 3
up 3
down 7
forward 9
forward 2
up 8
up 6
up 3
down 5
forward 8
down 8
down 6
forward 4
down 2
down 8
forward 8
up 7
up 4
up 5
down 4
up 6
forward 2
forward 9
down 9
forward 6
down 5
down 7
forward 5
up 5
forward 2
up 7
up 3
down 8
forward 8
forward 3
down 2
down 5
forward 4
down 8
forward 5
forward 4
down 9
forward 1
down 4
up 5
forward 5
down 1
forward 4
down 4
forward 4
down 8
up 5
up 4
up 9
forward 2
forward 3
down 3
forward 2
down 6
down 6
down 5
forward 8
forward 3
up 1
down 9
down 4
down 1
up 4
forward 2
forward 3
down 4
up 4
forward 5
forward 2
up 2
forward 4
down 2
down 3
down 6
up 2
forward 8
forward 9
forward 1
down 1
up 7
up 4
forward 2
forward 4
forward 2
forward 8
down 9
down 5
down 1
down 1
down 6
forward 1
up 6
down 4
down 9
down 2
down 2
down 5
up 6
forward 4
forward 1
forward 2
forward 8
forward 2
down 6
forward 1
down 8
down 1
forward 2
forward 3
down 9
down 7
down 5
up 1
forward 1
down 5
down 4
forward 8
down 9
up 7
forward 6
forward 2
forward 8
down 9
down 1
up 5
down 5
down 3
forward 6
forward 5
forward 2
forward 6
up 4
forward 1
down 9
forward 5
up 1
down 5
down 6
forward 8
down 4
up 9
down 6
down 9
down 7
down 3
forward 7
down 5
up 6
forward 3
up 4
down 5
up 5
up 9
forward 9
forward 8
down 9
forward 9
down 2
forward 5
forward 5
forward 9
down 3
up 8
down 7
up 9
forward 8
forward 8
down 1
down 5
down 4
up 8
forward 4
forward 7
down 2
down 7
down 6
down 9
down 7
forward 5
forward 7
forward 5
forward 2
forward 7
up 2
down 8
down 9
down 5
down 9
forward 5
forward 8
forward 9
up 5
down 9
down 7
forward 4
down 6
up 5
up 8
down 3
down 2
up 7
forward 9
down 3
down 2
down 7
down 4
up 6
up 4
down 7
down 4
forward 5
forward 6
up 6
down 7
down 9
down 9
down 6
forward 8
forward 3
forward 5
up 1
up 8
forward 4
forward 6
down 5
down 4
forward 5
forward 9
down 4
up 3
up 8
down 7
up 8
forward 5
forward 3
up 4
up 9
forward 6
down 1
up 6
down 5
down 4
down 3
down 8
up 1
down 1
up 8
up 8
down 6
forward 4
forward 9
down 4
down 7
forward 9
forward 8
up 6
down 9
up 3
down 8
forward 4
forward 6
forward 9
up 7
down 2
forward 2
forward 1
forward 5
up 9
up 7
up 5
forward 4
forward 5
forward 4
up 5
forward 4
up 6
down 5
up 2
forward 5
forward 5
down 9
forward 7
down 9
up 4
up 9
forward 6
forward 7
down 2
forward 4
down 9
down 6
forward 1
forward 7
up 3
up 3
down 6
up 6
up 2
up 3
forward 7
up 4
forward 1
down 1
forward 2
forward 4
down 1
down 8
forward 5
forward 8
up 7
down 3
forward 3
forward 6
down 8
down 7
up 9
forward 3
up 1
down 8
forward 4
down 9
forward 3
forward 8
down 4
forward 4
forward 1
up 6
down 1
down 7
forward 8
down 9
down 8
down 7
forward 5
up 6
forward 5
up 1
down 3
down 7
down 4
forward 6
down 4
down 7
up 9
down 6
down 7
up 3
up 8
forward 3
forward 1
forward 5
down 5
forward 5
down 1
forward 9
up 5
forward 4
down 1
down 8
up 1
up 3
up 8
down 3
down 5
up 7
forward 4
down 7
forward 9
forward 7
forward 9
down 9
forward 3
forward 6
up 3
forward 4
forward 4

Writing input_p2.txt


In [ ]:
with open('input_p2.txt', 'r') as fd:
  input = []
  for line in fd.readlines():
    cmd = [0,0]
    dir, ammount = line.split(' ')
    if dir == 'forward':
      cmd = [int(ammount), 0]
    elif dir == 'up':
      cmd = [0, -int(ammount)]
    elif dir == 'down':
      cmd = [0, int(ammount)]
    else:
      raise Exception("Invalid command!")
    input.append(cmd)
    
input = np.array(input)
print(input)

[[ 8  0]
 [ 3  0]
 [ 0  8]
 ...
 [ 0 -3]
 [ 4  0]
 [ 4  0]]


In [ ]:
horizontal, depth = input.sum(axis = 0)
print(horizontal * depth)

1855814


## Part 2

In [ ]:
aim=0
horizontal = 0
depth = 0
for cmd in input:
  if cmd[0] == 0:
    aim += cmd[1] 
  else:
    horizontal += cmd[0]
    depth += aim * cmd[0]
 
print(horizontal * depth)

1845455714


# Problem 3

## Part 1

In [ ]:
#@title Input
%%file input_p3.txt
101010011010
101111111001
100100100000
000001010010
100100110011
000101100110
101011001001
100001111101
011001001101
010000110101
001111101111
010110111000
000010001100
011101111011
111111100111
010011101011
010110001000
001111001010
000110101011
011001110101
001110001111
101100001101
010111110010
110000000000
001101110110
111111101011
110011110110
100011110110
010111000001
111010100110
100001011101
110010110110
111101010111
000011110001
110101010000
111101101000
000001111110
100101000011
100101001010
111001001011
010110011110
111111010111
111000000111
101000101100
000000101100
111010001010
000000001110
011001111101
000000111010
010001000001
110101100000
101010100001
100011011010
110101000010
100110011100
110100110110
010000011101
111111101000
001000110111
000000001001
111000001011
101000000111
011010010001
000100001011
100100101100
100010101110
111000011100
011100000001
010111101110
101000010000
100101110100
101110000101
100001111001
110101001101
110100111001
011001100100
111101110010
010010111010
011100110011
100001100011
100001111011
010011001010
011000001110
000010101000
011111001010
101100000011
010011011010
000101110100
101111110011
011110011011
000101101001
110101111000
100001100001
001000110000
100101011001
001010100000
110001110110
000111010000
000001111010
100101010000
101000001111
111100011011
001010001011
010100110101
011110011110
101100101111
011110110111
000100011110
111101100000
100001111110
101000100110
101001000111
001100001010
110001011011
010001010110
001010110110
010101100011
100001001000
011111000100
010001011111
101100111001
100101101110
010111111100
011001011100
000110010000
101010110010
010001111110
001011100000
011110101000
110000110101
101101000100
101101111111
111010111110
000100110000
101111001110
110111100101
100011011100
111010011010
101010111110
001000011100
000110110100
000110110111
100110101111
101101010001
011011000010
110011010011
101010101001
010000001000
011111100000
110111111111
011010110101
101101011001
101001011001
100010010101
101100100101
010100100111
111100100100
001011001110
010111011100
110100010111
000110001111
010010110011
101110111101
011100001101
101100000001
110111000111
100100100111
001100011011
100110101100
110110101011
101101100011
101110111110
111101010001
011000100100
000110001100
111000111101
001011101011
101111001111
000010010100
111101001100
110000011010
001011111000
001000101111
000000111110
000111110111
000100101011
001011011110
011000100101
111010101111
010100001110
101101011101
000101000100
110010100001
001001011110
001011010000
110111101101
010011110001
111000111011
100101011110
111100100110
010100000000
100100011001
000001001111
101111111011
101100010101
111100011111
111010110101
100010010011
101011011000
101000011100
010100100010
101001111100
010000110000
111100010111
011000101000
110100110100
110001010110
110110110010
111100010010
000010101100
011110101111
100011000001
000000110101
111111100000
110110010011
000000010111
011001001010
001011001010
110110110001
110110110011
010010000101
101001001001
001010000001
100010001101
011101101101
100000010110
001100110110
000110110110
110001110100
111100000101
110101101100
100100101101
101111001100
100010011001
000011111001
010110101101
111111110101
011101010101
011011010001
111101110000
010101011110
011000111000
101111101101
111011110111
111111001101
101110101111
101000001101
101111101000
111101110001
011001100101
101000011010
111011100001
011000001111
001110000000
001010001110
100010001000
001011100111
101000000100
101011101000
000101111111
111010010101
000100000001
000011010100
010101111010
110110011001
001101001011
001101111111
111010000110
001100011010
000011111010
000100100010
100100001110
101001011111
101110001100
000000011000
100110010101
111100110101
000000011010
000101110010
000101101000
100100101110
011011111010
010111111001
010011001110
101010010111
101010001000
101010100111
011100000110
101101010011
010000001110
100100110100
111111100010
111111000100
000100111010
101011110110
011111001100
011101001110
011100111011
110011001011
111011111101
111011101100
100000100100
010001000111
111000001010
001111110000
010001010010
000110110000
100000100110
001010000110
010011011100
111000010011
110101001110
101010101110
111001001100
111001111011
110100011110
110011011001
010110010111
001111111101
110010000011
110100111010
110101110000
000101001111
010000010011
101011100101
011001010010
100110011001
111001101001
010100100001
000111011100
000011110110
111010101101
111110000111
010100101011
011100011110
100000011010
111111011011
100111110011
001111011100
001011000101
010010011111
101101100101
100110110100
011100010000
011101000100
000100101101
101100101000
110111111110
110100000111
101010001100
100111110101
100000010010
010110011111
010101100111
010101100001
001101011011
010101001100
000010110010
111001011010
001110111110
000100001110
111001110001
111100111110
001111101101
000111100110
101001100001
101000001110
100010101100
101101001110
001110011101
000111110100
100110100000
101001010010
111110011111
101101100110
101000000110
101000100011
001010101011
001110001101
100011010010
101111111100
010100111000
100110100100
001011110001
000011111111
111110110101
100011110100
101111010111
001100000111
001101111000
000011001000
011000101001
111101011011
100111010010
111101010011
001010010110
010111011101
111000110011
000110111010
101011001100
111011100110
001111000010
111111101100
110000000010
001010010001
011111110110
010110101110
110001010011
111000110101
110101110001
101101011011
011111110001
010010010110
010010100111
111001100101
011100001011
100001010100
000010110101
101010100100
010110100010
001000100110
011010000100
011111001000
100000000001
011010011000
101101001011
100011101001
011010000010
000011110101
001101100110
001000101010
101100010110
111010000001
110110100011
000100010100
100110100111
011011010011
011001110110
000000001111
000000001000
011100100110
000000001100
111010011101
110011010100
011100010011
011110001011
101110000000
101110001010
101001001000
100000000111
101011100110
101110110100
001001110011
110110001100
001100101001
001110000011
010111010111
101101000011
000000011101
001010011010
000001010100
011010001100
100001001101
010100010000
101111011110
001110110001
111111000001
011111010110
110100000000
010110100100
111001010110
111010100101
100100011011
110000100011
000001011001
110010110011
100010100100
011000010111
010101110000
111110100101
100010000000
101011000000
010100110110
100011011011
000010011000
110000001000
101101001100
100111000001
010000111011
111000000011
010010100101
100100101010
000011110111
110111101010
000000010110
100111001011
101000011001
010011100101
100111110100
001111001001
000111000101
000010010001
010101001101
111010010001
000011110000
100001101000
111111110100
010101011001
011110100101
001010100111
100001001111
001011010111
111111000101
111000001110
111000111100
110111111101
011101111110
111000011011
010111110101
001111101001
011100001010
000100101100
100111101010
010011011111
110010110101
111111010110
100011010111
100101111001
010100010010
110010000001
100111011101
111001100111
000001110001
010110101111
000111010101
100001101001
010000010000
001110101101
111101001111
010011101010
111110001011
110101000110
001001001011
001100001011
100010110000
010100010011
111000110111
100010100001
110000010000
000001111001
000100110110
101110001101
111011101010
110111100111
011101011000
011110111010
001001001110
101001011000
001010011110
011011011101
010100010110
011010010111
000110001010
111111111101
100110011111
011100011011
010001101111
100000100111
100011110101
111011101110
101001111010
110001010111
000010000101
001000000000
011000001101
110011000011
001000001001
110111001010
101110110001
111100010101
111110100011
010111101000
000011001001
001110000110
111001111110
111110100100
010000100111
111110101101
101001110111
011001110111
100000111101
100110111111
111001110011
100011110000
110001011100
011100001001
110101011001
101111001001
110111000110
111110100001
110011110011
111000101111
101111010110
110101010111
010010010101
101000011111
100010001110
000010111101
001001100001
010111010000
100011010100
011110101101
110001001110
101000001001
010000010001
110110000011
011011010010
111001100011
111000101000
010000001010
111110111001
111010111011
100001010111
010111100110
101001011100
111101010000
110110100000
111100110000
011101101100
101101101110
010001111001
000010011001
010000000101
100000111011
011100110001
110110100101
001100101101
110010100100
010101100000
100000101010
100011110010
110111001101
101101011000
111101001000
010101110101
010111110111
000110001101
110011101100
000100100011
101111111111
001001000000
000001101100
000110110101
010010110001
011101001011
111000011110
011111101100
011001101010
101101010100
110000110110
100000111110
110101000000
000110011000
111010000100
110101100111
110110001101
101001100011
011101110100
011010110110
100110101000
110000110000
001101011000
110101011011
011011111001
001010101100
101010000001
000111000000
001011100011
000001011101
011010011110
001100001110
001101000100
010110001101
111011100000
011001110001
001001110101
111100000111
101000110011
010011010000
101101011010
010101010011
100110010110
101101111101
011010111000
010001000000
001000010011
111101101101
110111010001
110101011110
001111110001
000110101110
000001100000
100110011011
101110111011
100111001100
101100010001
011011110100
010100011100
010010011100
101010110111
000111110011
101010001111
010001101011
101110101101
111000000000
000000010000
010101111001
111001010111
000101000001
010110010100
111111100101
101100110101
110011000100
111010010011
010100001000
110011001001
111101000010
000010001001
010111101111
000110001110
100000001011
001110111000
110001101011
111100011101
111100100101
010011111010
100100001100
100000011111
010000001101
111001010100
000101110000
111010110110
100110110000
101100000111
111010010010
110000110100
011101011101
010001000101
110000000011
110110110101
100110000010
010001010001
101001111000
111111001010
000000110011
010110100111
111110000101
000100011011
000101010101
010100111011
101010110000
101111000011
011001011101
111101111010
000000001011
000110110001
001001110010
001000100010
000001110111
000110000101
111100101011
100111000100
010011000000
001110110010
110010111010
011111111110
110101010100
011101101110
101111010010
111100100011
010011001111
011101010110
011111101111
011000010000
001001010110
101000010011
000111011111
100110000001
111001111010
001001111101
101000011011
001111111000
001111110011
110111011011
010100100110
001110101001
011100111101
111111101010
101100011010
001010110111
000000100011
001110100011
010110001001
111001011001
011010101101
110100111110
011111000001
110110011111
110100000010
010000110111
001100101000
101000011101
010100111101
111101000000
001001000110
001111011010
111010000011
000110101101
010000010111
001101101101
110100000101
000010110001
011000001000
010011100000
010100110100
101000100101
000000010101
111000000001
101001111110
101101000000
000000001010
001111010100
001110000010
110110011100
000111000010
011011100001
010011100100
110101001001
000001011110
101001011101
100111001001
011000000011
110110111000
100101111000
010101110111
100010000101
010011001011
011111100010
000000011011
111000100001
000011000110
111101001101
100011001111
100111010100
010011100010
100100111111
110001001010
100100111010
111001101101
000100110001
101111101100
001110010101
000010010000
011100010101
100100001011
000001110011
110111001000
001001100110
001100111111
100000100101
000110111110
101010110100
011001110011
100011000111
000100111100
010100001001
000110000100
001100110000
110111100011
010110010010
100010000010
100100111101
011000111101
000100110100
011101001000
110111010110
010111000000
010111110100
110111011000
101010000000
101001100101
111100001100
110010110010
010111001001
011101010001
011100010001
110011011010
100110000011
001111001100
100010110111
111000101100
000101101110
000100010101
010101001001
010101101000
101100101110
011011001000
111110010011
010111101101
000001111111
110111101001
010101010110
101100011011
011110110011
101011100011
110010111001
110010001111
001010111101
000101011110
111011111010
100100010011
000100000010
001110101011
001001110000
001011000001
101001000100
000111100010
010101110100
010111110000
111100011100
100001010011
111111001100
100010011000
110100011011
100111100111
111110001001
011000001001
001001100010
100001100111
001011100110
111001101010
111011111011
110011010001
100001100010
000010100011
100101011101
000111100101
110001100111
101000000101
011010000101
110000010011
010110000011
010101010001
111010101010
110111010010
111101011000
010010010000
001000101011
001001101010
011101100110
010001011000
101001101010
011110100000
011110110000
011010010000
010010100001
111001110010
101010000111
111101100001
111011000010
110000100101
100110011010
010000011011
100001001001
111100000000
001000011111
001001010010
110110110110
010111101100
010000101100
001110001110
011000010001
001101010000
100111111111
101110010111
001101100100
001000010010
010000000011
000110000010
000001101000

Overwriting input_p3.txt


In [ ]:
with open('input_p3.txt', 'r') as fd:
  input = []
  for line in fd.readlines():
    data = [int(bit) for bit in line[:12]]
    input.append(data)
  input = np.array(input)
  print(input)

[[1 0 1 ... 0 1 0]
 [1 0 1 ... 0 0 1]
 [1 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 1 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
def binary_to_decimal(binary):
  decimal = 0
  for i, bit in enumerate(reversed(binary)):
    decimal += 2**i * bit
  return decimal

gamma_rate_bool = (input.sum(axis=0) > len(input)//2)

gamma_rate = np.array([int(bit) for bit in gamma_rate_bool])
epsilon_rate = np.array([ int(not bit) for bit in gamma_rate_bool])

print(gamma_rate, binary_to_decimal(gamma_rate))
print(epsilon_rate, binary_to_decimal(epsilon_rate))
print(f"Product: {binary_to_decimal(gamma_rate) * binary_to_decimal(epsilon_rate)}")


[1 1 0 1 0 0 0 1 0 1 0 1] 3349
[0 0 1 0 1 1 1 0 1 0 1 0] 746
Product: 2498354


## Part 2

In [ ]:
index = np.arange(len(input))
for i in range(input.shape[1]):
  ones = (input[index][:,i] == 1).sum()
  zeros = len(input[index]) - ones
  most = 1 if ones >= zeros else 0
  print(f"i: {i}, #ones: {ones}, #zeros: {zeros}, most: {most}")
  index = index[input[index][:,i] == most]
  if len(index) == 1:
    break
print(i)
oxygen_generator_rating = input[index[0]]
print(oxygen_generator_rating, binary_to_decimal(oxygen_generator_rating))

i: 0, #ones: 512, #zeros: 488, most: 1
i: 1, #ones: 256, #zeros: 256, most: 1
i: 2, #ones: 143, #zeros: 113, most: 1
i: 3, #ones: 72, #zeros: 71, most: 1
i: 4, #ones: 33, #zeros: 39, most: 0
i: 5, #ones: 20, #zeros: 19, most: 1
i: 6, #ones: 8, #zeros: 12, most: 0
i: 7, #ones: 6, #zeros: 6, most: 1
i: 8, #ones: 2, #zeros: 4, most: 0
i: 9, #ones: 1, #zeros: 3, most: 0
i: 10, #ones: 1, #zeros: 2, most: 0
i: 11, #ones: 1, #zeros: 1, most: 1
11
[1 1 1 1 0 1 0 1 0 0 0 1] 3921


In [ ]:
x = np.array([1,1,0,1,0,1])
ones = (x == 1).sum()
zeros = len(x) - ones
print(ones, zeros)

4 2


In [ ]:
index = np.arange(len(input))
for i in range(input.shape[1]):
  ones = (input[index][:,i] == 1).sum()
  zeros = len(input[index]) - ones
  least = 0 if ones >= zeros else 1
  assert ones > 0
  assert zeros > 0
  print(f"i: {i}, #ones: {ones}, #zeros: {zeros}, least: {least}")
  index = index[input[index][:,i] == least]
  if len(index) == 1:
    break
CO2_scrubber_rating = input[index[0]]
print(CO2_scrubber_rating, binary_to_decimal(CO2_scrubber_rating))

i: 0, #ones: 512, #zeros: 488, least: 0
i: 1, #ones: 245, #zeros: 243, least: 0
i: 2, #ones: 113, #zeros: 130, least: 1
i: 3, #ones: 55, #zeros: 58, least: 1
i: 4, #ones: 32, #zeros: 23, least: 0
i: 5, #ones: 11, #zeros: 12, least: 1
i: 6, #ones: 6, #zeros: 5, least: 0
i: 7, #ones: 3, #zeros: 2, least: 0
i: 8, #ones: 1, #zeros: 1, least: 0
[0 0 1 1 0 1 0 0 0 1 0 0] 836


In [ ]:
print(binary_to_decimal(oxygen_generator_rating) * binary_to_decimal(CO2_scrubber_rating))

3277956


# Problem 4

## Part 1

In [5]:
#@title Input
%%file input_p4.txt
93,49,16,88,4,92,23,38,44,98,97,8,5,69,41,70,19,11,29,40,90,43,79,96,68,10,31,35,34,32,0,67,83,33,2,76,24,87,99,77,82,66,12,15,28,59,64,95,91,71,62,22,53,46,39,81,75,86,74,56,50,18,17,73,13,54,60,48,21,51,52,55,85,80,30,36,47,3,26,57,84,25,63,27,37,94,7,45,58,9,78,65,72,6,14,61,20,1,42,89

83 11 47 61 45
30 74 73 14 66
53 52 10 57 15
64 50 54 28 87
26 85 63 25 86

72  4 62 30 49
43 93 39 63 25
18 70 44 77 38
84  8 85  5 26
54 50 40 75  2

70 78 55 26 35
75 44 80 15 34
67 47 53 10 56
73 46 27 38 13
64 92 39 87 23

24 66 11 44 51
32 37 83 69 85
46 59 14 99 76
71 28 94 35 98
16 40 74 80  6

 1 55 42 59 70
87 81 68 83 56
12 21 20 49 84
89 92 94  2 76
 5 17 77  3 32

66 98 10 53 78
80 92 26 38 29
46 34 22 51  8
43 89 87 64 17
63 86 84 62 15

75 65 96 19 87
12 51 97 68  8
42 90 61 10 71
69 48  7 15 26
43 89 21 16 35

64 92 83  2 48
11 34 98 75 96
21  6 54 78 68
42 19 16 41  8
24 58 45 81 49

59 37 46  1 30
51  6 10 44 82
85  3 27 83 96
48 81 56 34 55
35 99 67 12 78

14 49 41 82 78
 8 70 29 72 32
61 16 19 68 38
93 46 48 42 31
45 36 84 54 11

96 14  1 71 91
 3 89 59 27  2
34 37  5 31  0
22 44 98 43 32
 6 66 95 40 46

75 57 76 50 84
32 59 35 12 86
81 77 42 13 21
91  3  9 44 96
 4 52 23 18 37

16 62 40  8 82
43 70 29 63  9
41 73 77 13 59
44  0 49 53 76
84 55 36 56 48

81 62 35 65 43
 6 84 67 44 48
31 56 73 69 33
66 92 40 77 55
 4 70 97 88 13

63  5 12 66 77
68 74 15 84 16
 1 45 72 54 42
58 33 35 65 21
73 60 67 10 95

 0 25 16 42 45
27 98 87 29  3
62  6 88 19 95
84 33 53 89 37
46 38 97 96 77

98 62  8 73 20
81 83 51 55 21
 4 13 70 60  1
32 82 12 22 61
79 40 92 76 36

91 52 17 13 76
25 79 88 90 87
41 58 89 30 66
56 49 69 35 61
44 57 81 34 43

69 88 87 72 84
36 55 13 11 27
47 40 34 99 38
23 18 96 57 28
41 67 26  6 54

39 69 49 40 86
 6 75 90 31 21
82 15 48 37 88
55 23  4  7 10
68 81 87 56 73

41 65 82 20 31
42 22 88 70 75
73 76 54 15 83
67 99 46 28 72
 9 51 57 96 38

 3  1 15 13 79
 7 94 77 86 30
54 39  9  5 43
66 34 92 87 88
59 93 32 48 51

98 21 19 76 97
93 83  5 24 99
14 80 85  7 92
 8 53  1 78 72
45 20  2 13  6

51 28 54 62 42
97 70 77 23 81
15 67 33 55  0
35 78 14 61  8
26 13 99 56 24

71 99  2 72 21
22 54 30 38 41
92 47 56 70 34
28 90  0 67 78
63 14 84 97 61

86 81 85 21 65
59 47 56 28 32
89 54 44 71  1
80 55 76 12 33
13 11 31 92 88

54 41  8 46 83
35  2 23 15 52
31 91 92 61 19
25 17 98 53 22
72 78 81 84 27

61 72 95 50 49
19 37 85 64 71
78 18 59 54 67
75 68 27 90  1
 8 62  3 32 83

 0 20 88 30 52
87 13 73  3 79
37 22 10 70 67
61 48 81 40 54
50 68 93  8 34

88 39  9 36 15
14 79  1 58 83
 4 73 42 55 37
 0 53 77 28  8
18 92 21 25 62

65 36 59 80 97
 6 60  3 95 52
20 10 78  1 46
45 26 38 96 25
37 85 19 98 75

27 47 38 62 86
16 35 87 46 74
52 94 25  9  2
61 88 51 90 68
79 72  1 20 82

 5 29  9 44 64
89 15 78 56  2
85 93 28 79 34
87 16 21 59 49
 8 39 71 57 75

 0 64 99 62 28
47  3 87 31  9
70 10 97 24 91
65 43 96 86 85
35 88 25 67 83

69 67  8 31 49
57 22 83 56 79
91 54 70 33 53
68 47 84 80 35
21  7 65  4 17

 4  2 18 62 13
74 31 60 59 16
71 43 86 17 93
70 81 50 53 64
51 96 49  7 47

51 96 12 23 18
27  2 35 55 50
92 44  4 49 85
40 58  6 13 16
98  5 48 74 57

88  3 15 45 95
59  2 58 98 77
62 89 80 11 74
10 49 48 72 76
86 61 53 60 44

77 85  1  3 76
94 30 83  6 39
80 92 24 31 46
64 47 65  7 84
23 86 79 82 34

99  5  2 23 53
78 79 55 96 84
91 43 47 69 63
80 29 94 14 32
 1 18 90 28 68

29 51 43 17  0
 4 44 48 93 40
52 11 75 50 88
34 95 47 68 55
84 54 19 12  5

26 98 34 92 53
80 69 68  5 71
 1 30 61 15 56
96 22 52 70 25
93  7 36 18 55

19 16  4 32 55
61 66 67 50 88
89 51 64 57 43
87 31 49 85  9
90 39 56 96 59

25 59 57 10 52
 8 50 28 71  3
99 78 47 31 42
 0 82 98 93  2
89 81 55 76 13

19 81 93 25 20
87 70 42 38 44
33 98 62 91 39
49 80 47 56 28
92 46  8 78 75

70 86 32 10 83
30 62 99 45 88
 6  5 43 22 16
57 48 49 18 68
33 28 80 94  9

85 65 83 59 44
52 24 87 31 56
17 94 73 43 58
10 23 46 36 89
53 28 63 62 70

72  7 99 40 77
68 71 12 19 97
54 73 64 43 11
44 29 58 75 78
21  6 30 90 28

97 32 21 48 25
67 58 64  0  1
50 49 27 70 43
76 22 12 51 37
93 20 62 36 26

76 69 52  2 67
13 18  1 62 81
94 43 99 10 45
17 55 19 44 78
46  3 16 74 73

23 17 66  2 78
44 53 67 19 69
94 43 85 34 14
26 63 40  1 27
95 48 20 72 64

49 96 17 42 53
 8 15 62  3 90
 9 57 61 82 46
95 44 75 27 23
10  6 24 63 98

80 35 65 55 37
64 91 77  3 94
46 24 97 87 78
60  2 61 23 32
51 92 59 73 25

68  5 32 99 70
18 43 96 63 52
88  3 59 76 25
65 48 72  2 24
67 41 60 44 87

12 48 72 86 93
27 36 96 51 21
 2 50 34 83  6
49 65 32 42 87
88 10 43 84 22

78 70 44 10 80
18 71 17 50 27
12 46 88  6 91
98  0 31 85 56
92 53 72 77 28

85 84  6 89 24
15 41 21 92 71
88 90 95 32 98
46 60 35 38 17
36 66 93 70 40

54  5 41 59 76
38 47 48 51 71
80 96 39 85  0
68 61 55 40 13
78 94 99 19 30

50  3 55 37 25
16 59 48 52 13
41 20 46 27 39
90 80 30 84 93
22 12 79 74  0

16 97  4 58 80
68 49  0 87 35
88 63  1 36 74
45 91 55 46 75
22 17 43 19 71

30 98 31 63 16
62  6  3  9 67
61 11 29 66 52
80 97 42 72 76
78 57 90 13 89

40 22  8 11 43
90 61 29 10 88
69 86 74 26 70
14 51 93 32 80
84 75 81 72 16

91 22 89 72 82
63 58 80 42 45
11 40 29 41 90
17 16 62 14 35
23  4 65 79  0

32 76 30  8 90
 0 89  1 95 48
40 44 68 49 37
35 26 81 51 21
47 19 83 91 71

 9 31 70 42 16
82  4 84 54 45
58 36 53 20 44
26  5 69 90 52
95 67 51  7 76

 5 64 51 63  8
80 22 85 35 16
31 99 68 53 65
58  2 32 83 59
92 93 18 56 62

32 94  9 68 79
26 34  7  1  0
95 56 69 29 20
18 55 25 15 88
54 97 61 51 10

25  9  1 70 80
14 75 58 30 81
45 19  2 41 95
93 21 74  7 59
34 89 52 78 54

81  1 61 92 51
97 35  3  7 39
76 62 32 26 90
71 72 19 31 15
45 57 82 14 24

66  6 27 11 81
40 60 48 75 91
86 31 62 36 72
54 76 25 44 74
84 29 20 53 68

80 33 97  7 51
74 66  6 67 83
76 68 87 90 91
 2 53 49 31 82
72 95 26 28 22

33  1 93  2  8
 7 19  6 51 47
63 68 26 90 54
59 22  9 46 28
40 20 80 86 15

47  5 23 64 31
54 44 51 14 21
24 25 93 62  0
41 15 56 91 40
48 17 69 11 81

59 27 47 82 44
78 89 34  1 23
31 91 35 30 52
48 15 32 43  5
42 41 12 53 77

83  8 74 12  4
45 56 22 68 50
99  2 55 62 90
36 14  3 33 93
43 26 85 96 61

13 33 85 32 84
41 66 48  9 11
70 80 45 82 34
74 94 67 58 98
89  8 39 51 64

20 23 32 57 52
17  7 86 90 75
78 44 43 41 12
29 92  0 35 48
15 61 42 74 21

76 92 73 16  2
78 18 91 86 51
70 66 11 12 79
44 28 49 56 80
64 74 67 46 20

56 87 96 62 53
63  7 47 39 66
61 78 23 33 10
65 76 19  3 94
25 84 90 68 79

33 79 70 88 61
99 23 76 37 66
16 81 67 46 49
91 73 83 44 18
28 59 85 55 21

15 44 70 23 43
94 48  8 77 28
53 63 17 83 69
25 74 40 11 35
78 36 31 85 84

73 80 31 90 20
53 60  1 87 33
51 89 47 32 22
71 15 55 26  5
77 81 39 11 94

 2 15 79 22 50
63  8 66 53 13
26  4 16 20 59
47 93 80 77 38
 7 52 92 74 99

68 10 22 61  7
50 63 93 27 54
32 79 20 62 88
13 77 64 89 65
97 41 39 38 75

81 29 64 14 80
25 57 94 13 60
58 33 63 98 42
46 10 17 76 61
 2  1 68 56 45

49 23 82 10 56
71 25 85 26 58
65 37 88  7  3
34 80 66 63 74
57 51 35 39 91

35 48  3 22 38
49 19 71 55 62
34 96 69 32 58
40 81 56 36 50
15 52 46 53 90

25  5 93 72 26
88 84 75 87 34
69 60 79 48 50
27 73 33 55 47
65 62 74 46  4

86 82 78 17 16
72 36 76 20 68
69 95 58 37 80
92 97 28 30  7
 6 15  8 57 54

50 64 61  0 66
33 44 46 16 17
85 67 76 30 28
25 69 82 54  2
24 96  5 68  6

 7 98 31  2 11
13 92  4 72 73
62 29 15 47 40
21 90 57 89 76
81 66 88 12 82

37 45 19 78 73
82 68 96 26 51
35 28 13 12 98
40 47 59 10 18
 3 88  6 69 29

62 45  2 46 90
52 25 50 13  1
64 47 73 54 79
33 36 92 15 77
28  4 83 63  5

72 63 57 95 16
17 70 48 23 39
65 96 87 85 33
75 81 82 64 19
80 66  5 58 83

19  9 40 16 33
51 87 66 59 49
94 61 83 81  2
84 27 63 54 10
 8 95 88 42  6

 4 37 62 80 10
35 98 27 93 69
96 43 65 90  1
23 60 53 44 99
28 38 68 17 71

61 45 93 95 91
35 43 76 98 41
89 21 87 23 99
 8 81 58 12  0
32 24 15 70 96

91 59 26 69 61
16  2 45 34 66
95 62 78 82 12
98 41 30 49 50
32 22 53  8  7

94 50 23 64 46
90 19 68 93 76
63 49  9 44 89
83 88 36 55  6
22 14 85 58 70

89 97 86 21  4
57 29 17 46 22
25 10 49 74 63
24 23 93 56 11
37 48 82 55 88

Overwriting input_p4.txt


In [18]:
def get_board(lines):
  board = []
  for line in lines:
    board.append([int(x) for x in line.split()])
  return board 

with open('input_p4.txt', 'r') as fd:
  lines = fd.readlines()
  draws = [int(draw) for draw in lines[0].split(',')]
  boards = []
  for i in range(len(lines[1:])//6):
    board = get_board(lines[(i*6 + 2):(i*6 + 7)])
    boards.append(board)
  boards = np.array(boards)

print(draws)
print(boards[:2])

[93, 49, 16, 88, 4, 92, 23, 38, 44, 98, 97, 8, 5, 69, 41, 70, 19, 11, 29, 40, 90, 43, 79, 96, 68, 10, 31, 35, 34, 32, 0, 67, 83, 33, 2, 76, 24, 87, 99, 77, 82, 66, 12, 15, 28, 59, 64, 95, 91, 71, 62, 22, 53, 46, 39, 81, 75, 86, 74, 56, 50, 18, 17, 73, 13, 54, 60, 48, 21, 51, 52, 55, 85, 80, 30, 36, 47, 3, 26, 57, 84, 25, 63, 27, 37, 94, 7, 45, 58, 9, 78, 65, 72, 6, 14, 61, 20, 1, 42, 89]
[[[83 11 47 61 45]
  [30 74 73 14 66]
  [53 52 10 57 15]
  [64 50 54 28 87]
  [26 85 63 25 86]]

 [[72  4 62 30 49]
  [43 93 39 63 25]
  [18 70 44 77 38]
  [84  8 85  5 26]
  [54 50 40 75  2]]]


In [81]:
def has_won(board, draws):
  has_won = False

  # Mark board_bool based on draws
  board_bool = np.array([value in draws for value in board.reshape(-1)]).reshape(5,5)

  # Check rows and cols for victory
  for i in range(5):
    if board_bool[i,:].all() or board_bool[:,i].all():
      has_won = True
      break
  return has_won

def get_score(board, draws):
  board_bool = np.array(
    [value in draws for value in board.reshape(-1)]
  ).reshape(5,5)
  board_score = board[np.invert(board_bool)].sum() * draws[-1]
  return board_score

In [82]:
# Finding Winner board
winner_board = None
winner_draws = None
for l in range(len(draws)):
  for board in boards:
    if has_won(board, draws[:l]):
      winner_board = board
      winner_draws = draws[:l]
      break
  if winner_board is not None:
    break

print(winner_board)
print(winner_draws)
print(f"winner_board_score: {get_score(winner_board, winner_draws)}")

[[91 22 89 72 82]
 [63 58 80 42 45]
 [11 40 29 41 90]
 [17 16 62 14 35]
 [23  4 65 79  0]]
[93, 49, 16, 88, 4, 92, 23, 38, 44, 98, 97, 8, 5, 69, 41, 70, 19, 11, 29, 40, 90]
winner_board_score: 82440


## Part 2

In [83]:
# Finding Loser board
loser_board = None
loser_draws = None
for l in reversed(range(len(draws))):
  for board in boards:
    if not has_won(board, draws[:l]):
      loser_board = board
      loser_draws = draws[:l+1]
      break
  if loser_board is not None:
    break

print(loser_board)
print(loser_draws)
print(f"loser_board_score: {get_score(loser_board, loser_draws)}")

[[81 29 64 14 80]
 [25 57 94 13 60]
 [58 33 63 98 42]
 [46 10 17 76 61]
 [ 2  1 68 56 45]]
[93, 49, 16, 88, 4, 92, 23, 38, 44, 98, 97, 8, 5, 69, 41, 70, 19, 11, 29, 40, 90, 43, 79, 96, 68, 10, 31, 35, 34, 32, 0, 67, 83, 33, 2, 76, 24, 87, 99, 77, 82, 66, 12, 15, 28, 59, 64, 95, 91, 71, 62, 22, 53, 46, 39, 81, 75, 86, 74, 56, 50, 18, 17, 73, 13, 54, 60, 48, 21, 51, 52, 55, 85, 80, 30, 36, 47, 3, 26, 57, 84, 25, 63, 27, 37, 94]
loser_board_score: 20774


# Problem 5

## Part 1

In [84]:
#@title Input
%%file input_p5.txt
959,103 -> 139,923
899,63 -> 899,53
591,871 -> 364,644
739,913 -> 310,484
460,309 -> 460,705
351,389 -> 351,837
420,55 -> 420,541
916,520 -> 382,520
136,604 -> 295,604
343,59 -> 142,59
951,206 -> 806,206
984,950 -> 61,27
739,388 -> 988,388
374,370 -> 644,370
403,504 -> 798,899
943,535 -> 229,535
149,227 -> 583,661
62,126 -> 62,352
131,391 -> 131,717
254,944 -> 254,220
572,111 -> 572,47
336,249 -> 830,743
898,858 -> 203,163
203,320 -> 825,942
19,318 -> 19,120
740,432 -> 740,39
591,383 -> 220,754
445,592 -> 19,592
202,370 -> 837,370
473,916 -> 600,789
118,955 -> 884,189
377,376 -> 533,532
160,264 -> 160,62
627,572 -> 627,679
217,690 -> 217,629
685,323 -> 866,504
391,309 -> 493,207
872,776 -> 357,776
116,326 -> 116,426
82,900 -> 832,900
594,862 -> 594,593
802,636 -> 802,223
862,226 -> 862,787
313,573 -> 834,573
145,631 -> 13,499
545,433 -> 420,308
427,623 -> 427,808
898,120 -> 511,120
859,811 -> 859,28
715,958 -> 715,893
115,234 -> 484,234
125,253 -> 50,253
737,265 -> 158,265
523,965 -> 523,983
118,51 -> 118,766
455,774 -> 455,357
680,881 -> 925,881
191,186 -> 187,186
821,629 -> 792,658
397,906 -> 397,962
988,811 -> 988,427
91,733 -> 519,733
46,172 -> 566,172
740,619 -> 880,759
609,465 -> 609,702
289,211 -> 289,620
622,135 -> 622,929
113,53 -> 872,53
559,713 -> 559,132
894,237 -> 211,920
237,259 -> 237,39
738,542 -> 976,542
163,34 -> 525,34
681,672 -> 264,255
37,827 -> 722,827
60,803 -> 514,349
433,866 -> 433,257
379,493 -> 379,643
697,588 -> 192,83
875,646 -> 318,89
634,983 -> 634,111
636,69 -> 636,41
911,780 -> 701,570
792,71 -> 956,71
682,338 -> 608,412
257,768 -> 450,575
112,25 -> 795,708
730,86 -> 730,65
966,785 -> 789,608
390,263 -> 483,356
90,852 -> 90,471
507,914 -> 769,914
803,535 -> 803,245
710,787 -> 570,787
138,842 -> 270,710
862,988 -> 862,656
56,408 -> 849,408
16,10 -> 979,973
982,14 -> 12,984
647,915 -> 38,306
797,487 -> 19,487
539,933 -> 924,933
509,734 -> 176,734
813,505 -> 976,505
474,987 -> 474,896
21,200 -> 164,200
986,973 -> 31,18
919,830 -> 111,22
32,574 -> 456,150
743,595 -> 842,595
623,306 -> 722,306
878,367 -> 519,367
924,221 -> 924,231
86,950 -> 773,263
950,248 -> 537,248
149,155 -> 962,968
449,568 -> 179,568
186,304 -> 868,986
921,320 -> 639,602
602,262 -> 602,500
602,33 -> 602,248
380,731 -> 423,774
535,110 -> 638,110
552,317 -> 552,75
173,667 -> 173,847
707,480 -> 195,480
833,398 -> 267,964
276,716 -> 413,716
342,816 -> 922,816
24,184 -> 715,875
762,330 -> 717,285
718,886 -> 718,551
707,834 -> 707,704
479,578 -> 161,896
145,297 -> 145,435
760,651 -> 536,875
954,629 -> 954,816
305,949 -> 305,919
55,132 -> 55,233
469,85 -> 439,85
653,990 -> 536,990
876,531 -> 432,87
698,207 -> 698,672
11,70 -> 766,825
591,357 -> 30,918
697,987 -> 697,823
610,903 -> 370,663
319,678 -> 319,504
337,150 -> 309,150
876,57 -> 311,57
673,268 -> 345,596
895,364 -> 518,741
327,662 -> 941,48
77,709 -> 110,742
194,78 -> 661,78
587,24 -> 825,24
503,317 -> 719,317
459,632 -> 704,387
717,292 -> 835,292
912,927 -> 72,87
510,527 -> 146,527
336,771 -> 336,266
566,961 -> 496,961
969,335 -> 122,335
925,443 -> 925,397
316,812 -> 606,812
815,795 -> 116,795
169,36 -> 354,36
358,274 -> 389,274
302,147 -> 839,684
762,372 -> 972,372
172,721 -> 682,211
265,150 -> 248,167
753,559 -> 307,559
823,121 -> 823,126
498,856 -> 498,135
75,977 -> 75,381
541,297 -> 541,320
735,108 -> 866,108
434,907 -> 868,907
915,959 -> 255,959
967,666 -> 967,209
361,600 -> 361,222
314,580 -> 314,497
175,989 -> 523,641
957,97 -> 311,743
956,227 -> 12,227
95,364 -> 95,742
857,141 -> 193,805
388,651 -> 468,731
582,177 -> 324,177
68,272 -> 68,720
543,490 -> 910,490
508,281 -> 902,281
823,380 -> 823,296
23,10 -> 946,933
813,70 -> 813,450
881,893 -> 598,893
535,781 -> 973,781
80,890 -> 909,61
604,630 -> 307,927
836,917 -> 184,917
76,727 -> 10,727
727,235 -> 727,578
629,80 -> 892,80
110,655 -> 663,102
985,12 -> 11,986
830,656 -> 830,761
660,869 -> 660,543
381,340 -> 381,562
392,735 -> 417,735
855,24 -> 320,24
801,669 -> 278,146
730,964 -> 107,964
523,158 -> 385,20
27,833 -> 27,987
569,707 -> 500,707
527,732 -> 527,424
74,88 -> 273,287
143,974 -> 143,735
247,388 -> 813,954
577,14 -> 945,382
49,43 -> 953,947
332,210 -> 332,143
69,280 -> 949,280
25,923 -> 904,44
306,569 -> 306,470
158,273 -> 113,228
771,355 -> 694,278
515,115 -> 245,385
427,381 -> 427,729
16,987 -> 987,16
319,463 -> 319,234
854,977 -> 66,189
794,194 -> 794,183
576,65 -> 576,843
37,964 -> 734,964
740,920 -> 740,877
245,487 -> 245,957
404,794 -> 853,794
660,656 -> 660,756
921,605 -> 127,605
650,894 -> 916,894
968,893 -> 481,406
986,979 -> 21,14
154,303 -> 498,647
720,338 -> 229,338
62,936 -> 62,897
55,820 -> 55,923
812,31 -> 551,31
338,466 -> 951,466
663,492 -> 775,604
449,602 -> 39,602
44,403 -> 44,144
58,62 -> 339,62
713,730 -> 713,502
704,525 -> 976,797
372,709 -> 372,680
709,387 -> 153,387
922,103 -> 615,103
629,839 -> 121,839
206,722 -> 529,722
232,556 -> 422,746
300,470 -> 300,726
376,820 -> 622,574
834,25 -> 255,604
271,200 -> 271,875
804,934 -> 872,934
900,753 -> 900,632
604,323 -> 604,70
890,911 -> 890,41
464,169 -> 812,169
850,196 -> 850,903
34,574 -> 34,54
718,59 -> 462,315
431,923 -> 737,923
433,573 -> 433,420
297,478 -> 297,775
756,545 -> 544,545
247,708 -> 247,702
736,835 -> 173,272
319,85 -> 319,827
931,775 -> 683,775
292,315 -> 451,315
397,435 -> 380,435
987,978 -> 82,73
227,349 -> 227,724
349,741 -> 899,191
965,325 -> 765,125
849,306 -> 88,306
516,548 -> 516,902
919,395 -> 568,395
736,507 -> 192,507
960,782 -> 196,18
431,413 -> 510,492
911,696 -> 911,830
888,225 -> 174,225
57,790 -> 57,953
858,399 -> 119,399
59,302 -> 290,302
456,907 -> 456,599
374,743 -> 374,565
183,107 -> 183,171
58,699 -> 288,699
886,970 -> 109,193
940,395 -> 806,261
781,480 -> 596,665
456,724 -> 265,724
414,406 -> 299,521
115,898 -> 115,863
34,543 -> 34,496
900,843 -> 900,457
165,209 -> 189,209
976,627 -> 539,190
252,202 -> 137,202
584,339 -> 550,373
580,153 -> 380,353
232,412 -> 650,830
910,833 -> 88,11
418,245 -> 829,245
298,823 -> 907,214
91,876 -> 495,876
315,874 -> 650,539
907,635 -> 365,635
339,313 -> 320,313
362,435 -> 362,938
152,664 -> 152,391
253,210 -> 272,210
216,396 -> 216,726
852,912 -> 15,75
882,828 -> 689,828
674,533 -> 674,523
469,719 -> 469,79
733,169 -> 665,101
734,632 -> 717,632
615,565 -> 615,114
979,720 -> 243,720
827,125 -> 827,919
605,419 -> 601,419
749,13 -> 433,329
990,902 -> 990,843
186,679 -> 186,457
374,796 -> 736,796
133,867 -> 133,801
757,622 -> 812,567
351,179 -> 351,509
214,748 -> 575,748
177,903 -> 861,219
747,981 -> 747,64
588,125 -> 588,557
464,338 -> 769,338
645,669 -> 125,149
579,352 -> 138,352
77,605 -> 520,605
698,816 -> 698,917
112,943 -> 112,834
731,720 -> 724,720
887,440 -> 976,351
676,301 -> 676,741
870,732 -> 870,648
250,826 -> 413,826
399,720 -> 543,864
834,93 -> 468,459
415,475 -> 415,641
793,415 -> 47,415
365,476 -> 365,31
195,154 -> 813,154
503,605 -> 773,605
553,121 -> 851,121
25,420 -> 423,818
943,110 -> 258,110
775,436 -> 826,436
16,161 -> 16,889
702,555 -> 920,555
589,858 -> 533,802
932,404 -> 932,539
647,275 -> 647,962
87,179 -> 326,179
931,588 -> 931,287
868,96 -> 557,96
879,28 -> 875,28
375,132 -> 287,44
484,352 -> 644,512
448,566 -> 448,214
734,460 -> 717,460
550,379 -> 550,674
964,184 -> 820,328
167,504 -> 387,504
594,777 -> 952,777
328,712 -> 837,712
600,773 -> 546,773
955,954 -> 82,81
863,790 -> 863,86
831,773 -> 32,773
987,11 -> 19,979
901,878 -> 901,177
427,341 -> 721,635
690,835 -> 567,835
557,724 -> 14,181
591,20 -> 205,406
846,865 -> 846,859
644,646 -> 742,548
187,376 -> 187,563
367,806 -> 250,923
332,731 -> 468,731
378,431 -> 469,431
844,949 -> 844,452
172,320 -> 735,320
597,639 -> 633,639
353,831 -> 353,307
355,392 -> 465,392
624,179 -> 548,255
441,928 -> 401,888
442,680 -> 442,569
567,385 -> 908,44
10,561 -> 603,561
851,289 -> 13,289
832,143 -> 832,64
366,851 -> 67,851
890,404 -> 333,961
83,22 -> 963,902
10,783 -> 821,783
369,481 -> 369,611
943,356 -> 846,356
675,95 -> 335,435
442,928 -> 442,764
500,643 -> 334,643
90,207 -> 620,207
520,412 -> 745,187
586,89 -> 613,89
411,424 -> 595,424
938,650 -> 232,650
216,773 -> 76,773
895,690 -> 895,294
250,886 -> 250,605
296,422 -> 863,989
534,626 -> 534,707
577,608 -> 52,83
61,674 -> 714,21
844,126 -> 844,694
565,541 -> 253,229
62,24 -> 986,948
588,901 -> 588,212
541,508 -> 541,141
516,376 -> 589,449
390,215 -> 749,215
324,878 -> 296,850
592,408 -> 592,158
433,207 -> 172,207
139,72 -> 139,121
471,676 -> 268,676
374,433 -> 374,95
672,459 -> 640,427
348,577 -> 843,82
903,466 -> 903,348
437,759 -> 726,470
152,101 -> 325,274
933,897 -> 335,897
516,877 -> 505,866
890,715 -> 570,715
78,124 -> 871,917
360,645 -> 967,645
645,271 -> 645,57
693,878 -> 693,159
49,77 -> 49,744
935,914 -> 97,76
941,726 -> 941,464
756,985 -> 756,480
887,378 -> 887,529
405,925 -> 405,533
533,156 -> 201,156
565,535 -> 120,90
51,15 -> 967,931
660,218 -> 660,339
522,682 -> 571,682
958,899 -> 729,899
521,687 -> 288,687
643,148 -> 468,323
989,971 -> 68,50
729,273 -> 311,691
245,205 -> 305,205
634,747 -> 634,605
280,407 -> 488,199
109,931 -> 706,334
849,694 -> 615,928
794,84 -> 218,84
669,184 -> 865,184
936,834 -> 234,132
691,445 -> 914,668
423,161 -> 515,69
81,674 -> 37,674
292,423 -> 292,741
188,306 -> 844,962
204,309 -> 204,705
961,652 -> 746,652
985,987 -> 11,13
139,153 -> 936,950
436,978 -> 244,978
921,633 -> 921,340
872,63 -> 233,63

Writing input_p5.txt


In [134]:
with open('input_p5.txt', 'r') as fd:
  line_segments = []
  for line in fd.readlines():
    start, end = line.split('->')
    x1,y1 = start.split(',')
    x2,y2 = end.split(',')
    line_segments.append([int(x1), int(y1), int(x2), int(y2)])
  line_segments = np.array(line_segments)

In [132]:
# Test Example
line_segments = np.array([
  [0,9,5,9],
  [8,0,0,8],
  [9,4,3,4],
  [2,2,2,1],
  [7,0,7,4],
  [6,4,2,0],
  [0,9,2,9],
  [3,4,1,4],
  [0,0,8,8],
  [5,5,8,2]
])

In [121]:
xmax = max(line_segments[:,0].max(), line_segments[:,2].max())
ymax = max(line_segments[:,1].max(), line_segments[:,3].max())

grid = np.zeros((xmax+1, ymax+1))
for line_segment in line_segments:
  x1, y1, x2, y2 = line_segment
  if y1 == y2: # Horizontal Line Segment
    grid[y1, min(x1,x2):max(x1,x2)+1] += 1
  elif x1 == x2: # Vertical Line Segment
    grid[min(y1,y2):max(y1,y2)+1, x1] += 1
  
print(grid)
print(f"Result: {(grid>=2).sum()}")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Result: 7318


## Part 2

In [135]:
xmax = max(line_segments[:,0].max(), line_segments[:,2].max())
ymax = max(line_segments[:,1].max(), line_segments[:,3].max())

grid = np.zeros((xmax+1, ymax+1))
for line_segment in line_segments:
  x1, y1, x2, y2 = line_segment
  if y1 == y2: # Horizontal Line Segment
    grid[y1, min(x1,x2):max(x1,x2)+1] += 1
  elif x1 == x2: # Vertical Line Segment
    grid[min(y1,y2):max(y1,y2)+1, x1] += 1
  else: # Diagonal Line
    xs = range(x1,x2-1,-1) if x1>x2 else range(x1,x2+1)
    ys = range(y1,y2-1,-1) if y1>y2 else range(y1,y2+1)
    for x, y in zip(xs, ys):
      grid[y, x] += 1
  
print(grid)
print(f"Result: {(grid>=2).sum()}")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Result: 19939


# Problem 6

## Part 1 and Part 2

In [194]:
initial_state = [3,5,3,5,1,3,1,1,5,5,1,1,1,2,2,2,3,1,1,5,1,1,5,5,3,2,2,5,4,4,1,5,1,4,4,5,2,4,1,1,5,3,1,1,4,1,1,1,1,4,1,1,1,1,2,1,1,4,1,1,1,2,3,5,5,1,1,3,1,4,1,3,4,5,1,4,5,1,1,4,1,3,1,5,1,2,1,1,2,1,4,1,1,1,4,4,3,1,1,1,1,1,4,1,4,5,2,1,4,5,4,1,1,1,2,2,1,4,4,1,1,4,1,1,1,2,3,4,2,4,1,1,5,4,2,1,5,1,1,5,1,2,1,1,1,5,5,2,1,4,3,1,2,2,4,1,2,1,1,5,1,3,2,4,3,1,4,3,1,2,1,1,1,1,1,4,3,3,1,3,1,1,5,1,1,1,1,3,3,1,3,5,1,5,5,2,1,2,1,4,2,3,4,1,4,2,4,2,5,3,4,3,5,1,2,1,1,4,1,3,5,1,4,1,2,4,3,1,5,1,1,2,2,4,2,3,1,1,1,5,2,1,4,1,1,1,4,1,3,3,2,4,1,4,2,5,1,5,2,1,4,1,3,1,2,5,5,4,1,2,3,3,2,2,1,3,3,1,4,4,1,1,4,1,1,5,1,2,4,2,1,4,1,1,4,3,5,1,2,1]

In [191]:
# Example input
initial_state = [3,4,3,1,2]

In [195]:
def get_fish_per_state(initial_state, days):
  fish_per_state = np.zeros(9, dtype = np.uint64)
  for state in initial_state:
    fish_per_state[state] += 1

  for day in range(days):
    give_birth = fish_per_state[0]
    fish_per_state[0:8] = fish_per_state[1:9]
    fish_per_state[6] += give_birth
    fish_per_state[8] = give_birth
  
  return fish_per_state

In [196]:
print(f"Total fish after 80 days: {get_fish_per_state(initial_state, 80).sum()}")
print(f"Total fish after 256 days: {get_fish_per_state(initial_state, 256).sum()}")

Total fish after 80 days: 365862
Total fish after 256 days: 1653250886439
